# Generated by Django 5.1.2 on 2024-11-12 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_question_stage_userresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='diagnosis',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='option',
            name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='stage',
        ),
        migrations.AddField(
            model_name='option',
            name='anxiety_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='option',
            name='depression_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='option',
            name='dissociative_precentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='option',
            name='eating_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='option',
            name='mood_disorder_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='option',
            name='neurocognitive_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='option',
            name='neurodevelopmental_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='option',
            name='obsessive_compulsive_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='option',
            name='option_text',
            field=models.TextField(default='Default option text'),
        ),
        migrations.AddField(
            model_name='option',
            name='personality_precentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='option',
            name='psychotic_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='option',
            name='self_harm_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='option',
            name='sleep_wake_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='option',
            name='somatic_disorder_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='option',
            name='stress_precentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='option',
            name='substance_use_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='option',
            name='trauma_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(default='stage_1', max_length=50),
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.question'),
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
    ]
