# Generated by Django 5.1.2 on 2024-11-12 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_option_diagnosis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='sleep_wake_percentage',
            new_name='sleep_disorder_percentage',
        ),
    ]
