# Generated by Django 5.1.2 on 2024-11-12 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_sleep_wake_percentage_option_sleep_disorder_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='myapp.question'),
        ),
    ]
