# Generated by Django 5.1.2 on 2024-11-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_book_breathingexercise_movie_music_podcast_workout_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='dissociative_precentage',
            new_name='dissociative_disorders_percentage',
        ),
        migrations.AlterField(
            model_name='option',
            name='option_text',
            field=models.TextField(),
        ),
    ]
